language: php
php composer.phar install
php:
  - 7.0
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly
  - 5.4
  - 5.5

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist
   ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash


script:
  - ./vendor/bin/phpunit
   ## PHP_CodeSniffer
  - phpcs --report=emacs --standard=PSR2 . --ignore=vendor/*
  ## PHP Copy/Paste Detector
  - php phpcpd.phar --verbose .
  ## PHP Mess Detector
  - phpmd . text cleancode --exclude vendor
  - phpmd . text codesize --exclude vendor
  - phpmd . text controversial --exclude vendor
  - phpmd . text design --exclude vendor
  - phpmd . text naming --exclude vendor
  - phpmd . text unusedcode --exclude vendor
  ## PHPLOC
  - php phploc.phar . --exclude vendor
  - find ./ -type f -name \*.php -exec php -l {} \;
  
  
notifications:
  email:
    kayke.ducati@gmail.com
